Replace custom math lib with modules from QT
OpenSourceSourceTrail/Sourcetrail pull request #8
Opened 2024-10-25 13:32 UTC by Eng-MohamedHussien

- Delete all headers from math lib with their corresponding tests
- Use QVector2D & QVector4D instead of Vector2 & Vector4
- Update mocks to be compatible with QVector2D & QVector4D

Ticket: SOUR-63

2024-10-26 11:02 UTC, wow2006 commented on tests/integration/lib/CMakeLists.txt
> +           Qt5::Gui
You removed all tests why you added the gui library?

2024-10-30 17:42 UTC, wow2006 requested changes

2024-10-30 17:42 UTC, wow2006 commented on src/messaging/type/graph/MessageGraphNodeMove.h
> +      return result.str();
```suggestion
      return fmt::format(L"[{}, {}]", delta.x(), delta.x());
```

2024-10-30 17:42 UTC, wow2006 commented on src/lib_gui/qt/graphics/graph/QtGraphNode.cpp
> +  if(offset.x() != 0 || offset.y() != 0) {
comparing float with zero is not a good idea. Checl the following https://www.fitzgibbon.ie/floating-point-equality

2024-10-30 17:42 UTC, wow2006 commented on src/lib_gui/qt/graphics/graph/QtGraphNode.cpp
> +    setColumnSize(QVector2D());
```suggestion
    setColumnSize({});
```

2024-10-30 17:42 UTC, wow2006 commented on src/lib_gui/qt/graphics/graph/QtGraphNode.cpp
> +  setSize(QVector2D(size.width(), size.height()));
```suggestion
  setSize({size.width(), size.height()});
```

2024-10-30 17:42 UTC, wow2006 commented on src/lib_gui/qt/graphics/graph/QtGraphNode.cpp
> +  return QVector4D(pos.x(), pos.y(), pos.x() + size.x(), pos.y() + size.y());
```suggestion
  return {pos.x(), pos.y(), pos.x() + size.x(), pos.y() + size.y()};
```

2024-10-31 16:00 UTC, Eng-MohamedHussien commented on src/lib_gui/qt/graphics/graph/QtGraphNode.cpp
> +  return QVector4D(pos.x(), pos.y(), pos.x() + size.x(), pos.y() + size.y());
done

2024-10-31 16:00 UTC, Eng-MohamedHussien commented on src/lib_gui/qt/graphics/graph/QtGraphNode.cpp
> +  setSize(QVector2D(size.width(), size.height()));
done

2024-10-31 16:00 UTC, Eng-MohamedHussien commented on src/lib_gui/qt/graphics/graph/QtGraphNode.cpp
> +    setColumnSize(QVector2D());
done

2024-10-31 16:00 UTC, Eng-MohamedHussien commented on src/messaging/type/graph/MessageGraphNodeMove.h
> +      return result.str();
done

2024-11-01 15:34 UTC, Eng-MohamedHussien commented on src/lib_gui/qt/graphics/graph/QtGraphNode.cpp
> +  if(offset.x() != 0 || offset.y() != 0) {
done

2024-11-02 12:44 UTC, wow2006 approved these changes

2024-11-02 12:44 UTC, merged